Create document list page
SADiLaR/term_platform pull request #93
Opened 2024-07-22 05:41 UTC by OnaMosimege

Add template, view, and responsive  styling to document list page

2024-07-22 10:05 UTC, friedelwolff requested changes
The pagination isn't working correctly for me. I guess some of that is due to the `documents` vs `page_obj`, but even then I'm not convinced that filtering will continue working with pagination.

2024-07-23 04:43 UTC, OnaMosimege commented on app/app/views.py
> +            subjects_data = _("Multiple subjects")
will do

2024-07-23 04:44 UTC, OnaMosimege commented on app/app/views.py
> +        "documents": document_data,
I'll look into this

2024-07-23 05:08 UTC, OnaMosimege commented on app/templates/app/documents.html
> +  {% for document in documents %}
I see, will revisit this

2024-07-23 08:22 UTC, friedelwolff approved these changes
The paginator requires much more work, but I guess we need to merge this to get to other pressing matters.

2024-07-23 08:22 UTC, merged